<?php

namespace Mock\Delivery;

require_once dirname(__FILE__) . '/../../../../lib/Mock/Delivery/Address.php';

/**
 * Test class for Address.
 * Generated by PHPUnit on 2012-03-22 at 15:41:06.
 */
class AddressTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Address
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Address;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Mock\Delivery\Address::getPostcode
	 * @todo Implement testGetPostcode().
	 */
	public function testGetPostcode()
	{
		$this->assertEquals( 'SE10 0DX', $this->object->getPostcode() );
	}

}

?>
