<?php

namespace Delivery;

require_once dirname(__FILE__) . '/../../../lib/Delivery/Estimate.php';

/**
 * Test class for Estimate.
 * Generated by PHPUnit on 2012-03-22 at 13:03:22.
 */
class EstimateTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Estimate The estimate instance
	 */
	protected $_estimate;
	
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->_estimate = new Estimate( array(
			'strategy' => 'my-strategy',
			'consignment' => 'my-consignment',
			'destination' => 'my-destination',
			'cost' => 2.5,
			'time' => '5 Working Days'
		) );
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Delivery\Estimate::__call
	 */
	public function testCall()
	{
		$this->assertEquals( 'my-strategy', $this->_estimate->getStrategy() );
		$this->assertEquals( 'my-consignment', $this->_estimate->getConsignment() );
		$this->assertEquals( 'my-destination', $this->_estimate->getDestination() );
		$this->assertEquals( 2.5, $this->_estimate->getCost() );
		$this->assertEquals( '5 Working Days', $this->_estimate->getTime() );
	}
	
	/**
	 * @expectedException PHPUnit_Framework_Error 
	 */
	public function testInvalidCall()
	{
		$this->_estimate->getWiggle();
	}

}

?>
